//
//  Sprm.swift
//  
//
//  Created by Hugh Bellamy on 06/11/2020.
//

import DataStream

/// [MS-DOC] 2.2.5.1 Sprm
/// The Sprm structure specifies a modification to a property of a character, paragraph, table, or section.
public struct Sprm {
    public let ispmd: UInt16
    public let fSpec: Bool
    public let sgc: Sgc
    public let spra: UInt8
    
    public init(dataStream: inout DataStream) throws {
        try self.init(rawValue: try dataStream.read(endianess: .littleEndian))
    }
    
    public init(rawValue: UInt16) throws {
        /// ispmd (9 bits): An unsigned integer that, when combined with fSpec, specifies the property being modified. See the tables in the
        /// Single Property Modifiers section (2.6) for the complete list of valid ispmd, fSpec, spra combinations for each sgc.
        self.ispmd = rawValue & 0b111111111
        
        /// A - fSpec (1 bit): When combined with ispmd, specifies the property being modified. See the tables in the Single Property Modifiers
        /// section (2.6) for the complete list of valid ispmd, fSpec, spra combinations for each sgc.
        self.fSpec = ((rawValue >> 9) & 0b1) != 0
        
        /// sgc (3 bits): An unsigned integer that specifies the kind of document content to which this Sprm applies. The following table specifies
        /// the valid values and their meanings.
        /// Sgc Meaning
        /// 1 Sprm is modifying a paragraph property.
        /// 2 Sprm is modifying a character property.
        /// 3 Sprm is modifying a picture property.
        /// 4 Sprm is modifying a section property.
        /// 5 Sprm is modifying a table property.
        let sgcRaw = UInt8((rawValue >> 10) & 0b111)
        guard let sgc = Sgc(rawValue: sgcRaw) else {
            throw OfficeFileError.corrupted
        }
        
        self.sgc = sgc
        
        /// spra (3 bits): An unsigned integer that specifies the size of the operand of this Sprm. The following table specifies the valid values
        /// and their meanings.
        /// Spra Meaning
        /// 0 Operand is a ToggleOperand (which is 1 byte in size).
        /// 1 Operand is 1 byte.
        /// 2 Operand is 2 bytes.
        /// 3 Operand is 4 bytes.
        /// 4 Operand is 2 bytes.
        /// 5 Operand is 2 bytes.
        /// 6 Operand is of variable length. The first byte of the operand indicates the size of the rest of the operand, except in the cases of
        /// sprmTDefTable and sprmPChgTabs.
        /// 7 Operand is 3 bytes.
        self.spra = UInt8((rawValue >> 13) & 0b111)
    }
    
    public enum Sgc: UInt8 {
        case paragraph = 1
        case character = 2
        case picture = 3
        case section = 4
        case table = 5
    }
    
    public static let sprmCFRMarkDel = try! Sprm(rawValue: 0x0800)
    public static let sprmCFRMarkIns = try! Sprm(rawValue: 0x0801)
    public static let sprmCFFldVanish = try! Sprm(rawValue: 0x0802)
    public static let sprmCPicLocation = try! Sprm(rawValue: 0x6A03)
    public static let sprmCIbstRMark = try! Sprm(rawValue: 0x4804)
    public static let sprmCDttmRMark = try! Sprm(rawValue: 0x6805)
    public static let sprmCFData = try! Sprm(rawValue: 0x0806)
    public static let sprmCIdslRMark = try! Sprm(rawValue: 0x4807)
    public static let sprmCSymbol = try! Sprm(rawValue: 0x6A09)
    public static let sprmCFOle2 = try! Sprm(rawValue: 0x080A)
    public static let sprmCHighlight = try! Sprm(rawValue: 0x2A0C)
    public static let sprmCFWebHidden = try! Sprm(rawValue: 0x0811)
    public static let sprmCRsidProp = try! Sprm(rawValue: 0x6815)
    public static let sprmCRsidText = try! Sprm(rawValue: 0x6816)
    public static let sprmCRsidRMDel = try! Sprm(rawValue: 0x6817)
    public static let sprmCFSpecVanish = try! Sprm(rawValue: 0x0818)
    public static let sprmCFMathPr = try! Sprm(rawValue: 0xC81A)
    public static let sprmCIstd = try! Sprm(rawValue: 0x4A30)
    public static let sprmCIstdPermute = try! Sprm(rawValue: 0xCA31)
    public static let sprmCPlain = try! Sprm(rawValue: 0x2A33)
    public static let sprmCKcd = try! Sprm(rawValue: 0x2A34)
    public static let sprmCFBold = try! Sprm(rawValue: 0x0835)
    public static let sprmCFItalic = try! Sprm(rawValue: 0x0836)
    public static let sprmCFStrike = try! Sprm(rawValue: 0x0837)
    public static let sprmCFOutline = try! Sprm(rawValue: 0x0838)
    public static let sprmCFShadow = try! Sprm(rawValue: 0x0839)
    public static let sprmCFSmallCaps = try! Sprm(rawValue: 0x083A)
    public static let sprmCFCaps = try! Sprm(rawValue: 0x083B)
    public static let sprmCFVanish = try! Sprm(rawValue: 0x083C)
    public static let sprmCKul = try! Sprm(rawValue: 0x2A3E)
    public static let sprmCDxaSpace = try! Sprm(rawValue: 0x8840)
    public static let sprmCIco = try! Sprm(rawValue: 0x2A42)
    public static let sprmCHps = try! Sprm(rawValue: 0x4A43)
    public static let sprmCHpsPos = try! Sprm(rawValue: 0x4845)
    public static let sprmCMajority = try! Sprm(rawValue: 0xCA47)
    public static let sprmCIss = try! Sprm(rawValue: 0x2A48)
    public static let sprmCHpsKern = try! Sprm(rawValue: 0x484B)
    public static let sprmCHresi = try! Sprm(rawValue: 0x484E)
    public static let sprmCRgFtc0 = try! Sprm(rawValue: 0x4A4F)
    public static let sprmCRgFtc1 = try! Sprm(rawValue: 0x4A50)
    public static let sprmCRgFtc2 = try! Sprm(rawValue: 0x4A51)
    public static let sprmCCharScale = try! Sprm(rawValue: 0x4852)
    public static let sprmCFDStrike = try! Sprm(rawValue: 0x2A53)
    public static let sprmCFImprint = try! Sprm(rawValue: 0x0854)
    public static let sprmCFSpec = try! Sprm(rawValue: 0x0855)
    public static let sprmCFObj = try! Sprm(rawValue: 0x0856)
    public static let sprmCPropRMark90 = try! Sprm(rawValue: 0xCA57)
    public static let sprmCFEmboss = try! Sprm(rawValue: 0x0858)
    public static let sprmCSfxText = try! Sprm(rawValue: 0x2859)
    public static let sprmCFBiDi = try! Sprm(rawValue: 0x085A)
    public static let sprmCFBoldBi = try! Sprm(rawValue: 0x085C)
    public static let sprmCFItalicBi = try! Sprm(rawValue: 0x085D)
    public static let sprmCFtcBi = try! Sprm(rawValue: 0x4A5E)
    public static let sprmCLidBi = try! Sprm(rawValue: 0x485F)
    public static let sprmCIcoBi = try! Sprm(rawValue: 0x4A60)
    public static let sprmCHpsBi = try! Sprm(rawValue: 0x4A61)
    public static let sprmCDispFldRMark = try! Sprm(rawValue: 0xCA62)
    public static let sprmCIbstRMarkDel = try! Sprm(rawValue: 0x4863)
    public static let sprmCDttmRMarkDel = try! Sprm(rawValue: 0x6864)
    public static let sprmCBrc80 = try! Sprm(rawValue: 0x6865)
    public static let sprmCShd80 = try! Sprm(rawValue: 0x4866)
    public static let sprmCIdslRMarkDel = try! Sprm(rawValue: 0x4867)
    public static let sprmCFUsePgsuSettings = try! Sprm(rawValue: 0x0868)
    public static let sprmCRgLid0_80 = try! Sprm(rawValue: 0x486D)
    public static let sprmCRgLid1_80 = try! Sprm(rawValue: 0x486E)
    public static let sprmCIdctHint = try! Sprm(rawValue: 0x286F)
    public static let sprmCCv = try! Sprm(rawValue: 0x6870)
    public static let sprmCShd = try! Sprm(rawValue: 0xCA71)
    public static let sprmCBrc = try! Sprm(rawValue: 0xCA72)
    public static let sprmCRgLid0 = try! Sprm(rawValue: 0x4873)
    public static let sprmCRgLid1 = try! Sprm(rawValue: 0x4874)
    public static let sprmCFNoProof = try! Sprm(rawValue: 0x0875)
    public static let sprmCFitText = try! Sprm(rawValue: 0xCA76)
    public static let sprmCCvUl = try! Sprm(rawValue: 0x6877)
    public static let sprmCFELayout = try! Sprm(rawValue: 0xCA78)
    public static let sprmCLbcCRJ = try! Sprm(rawValue: 0x2879)
    public static let sprmCFComplexScripts = try! Sprm(rawValue: 0x0882)
    public static let sprmCWall = try! Sprm(rawValue: 0x2A83)
    public static let sprmCCnf = try! Sprm(rawValue: 0xCA85)
    public static let sprmCNeedFontFixup = try! Sprm(rawValue: 0x2A86)
    public static let sprmCPbiIBullet = try! Sprm(rawValue: 0x6887)
    public static let sprmCPbiGrf = try! Sprm(rawValue: 0x4888)
    public static let sprmCPropRMark = try! Sprm(rawValue: 0xCA89)
    public static let sprmCFSdtVanish = try! Sprm(rawValue: 0x2A90)
    public static let sprmPIstd = try! Sprm(rawValue: 0x4600)
    public static let sprmPIstdPermute = try! Sprm(rawValue: 0xC601)
    public static let sprmPIncLvl = try! Sprm(rawValue: 0x2602)
    public static let sprmPJc80 = try! Sprm(rawValue: 0x2403)
    public static let sprmPFKeep = try! Sprm(rawValue: 0x2405)
    public static let sprmPFKeepFollow = try! Sprm(rawValue: 0x2406)
    public static let sprmPFPageBreakBefore = try! Sprm(rawValue: 0x2407)
    public static let sprmPIlvl = try! Sprm(rawValue: 0x260A)
    public static let sprmPIlfo = try! Sprm(rawValue: 0x460B)
    public static let sprmPFNoLineNumb = try! Sprm(rawValue: 0x240C)
    public static let sprmPChgTabsPapx = try! Sprm(rawValue: 0xC60D)
    public static let sprmPDxaRight80 = try! Sprm(rawValue: 0x840E)
    public static let sprmPDxaLeft80 = try! Sprm(rawValue: 0x840F)
    public static let sprmPNest80 = try! Sprm(rawValue: 0x4610)
    public static let sprmPDxaLeft180 = try! Sprm(rawValue: 0x8411)
    public static let sprmPDyaLine = try! Sprm(rawValue: 0x6412)
    public static let sprmPDyaBefore = try! Sprm(rawValue: 0xA413)
    public static let sprmPDyaAfter = try! Sprm(rawValue: 0xA414)
    public static let sprmPChgTabs = try! Sprm(rawValue: 0xC615)
    public static let sprmPFInTable = try! Sprm(rawValue: 0x2416)
    public static let sprmPFTtp = try! Sprm(rawValue: 0x2417)
    public static let sprmPDxaAbs = try! Sprm(rawValue: 0x8418)
    public static let sprmPDyaAbs = try! Sprm(rawValue: 0x8419)
    public static let sprmPDxaWidth = try! Sprm(rawValue: 0x841A)
    public static let sprmPPc = try! Sprm(rawValue: 0x261B)
    public static let sprmPWr = try! Sprm(rawValue: 0x2423)
    public static let sprmPBrcTop80 = try! Sprm(rawValue: 0x6424)
    public static let sprmPBrcLeft80 = try! Sprm(rawValue: 0x6425)
    public static let sprmPBrcBottom80 = try! Sprm(rawValue: 0x6426)
    public static let sprmPBrcRight80 = try! Sprm(rawValue: 0x6427)
    public static let sprmPBrcBetween80 = try! Sprm(rawValue: 0x6428)
    public static let sprmPBrcBar80 = try! Sprm(rawValue: 0x6629)
    public static let sprmPFNoAutoHyph = try! Sprm(rawValue: 0x242A)
    public static let sprmPWHeightAbs = try! Sprm(rawValue: 0x442B)
    public static let sprmPDcs = try! Sprm(rawValue: 0x442C)
    public static let sprmPShd80 = try! Sprm(rawValue: 0x442D)
    public static let sprmPDyaFromText = try! Sprm(rawValue: 0x842E)
    public static let sprmPDxaFromText = try! Sprm(rawValue: 0x842F)
    public static let sprmPFLocked = try! Sprm(rawValue: 0x2430)
    public static let sprmPFWidowControl = try! Sprm(rawValue: 0x2431)
    public static let sprmPFKinsoku = try! Sprm(rawValue: 0x2433)
    public static let sprmPFWordWrap = try! Sprm(rawValue: 0x2434)
    public static let sprmPFOverflowPunct = try! Sprm(rawValue: 0x2435)
    public static let sprmPFTopLinePunct = try! Sprm(rawValue: 0x2436)
    public static let sprmPFAutoSpaceDE = try! Sprm(rawValue: 0x2437)
    public static let sprmPFAutoSpaceDN = try! Sprm(rawValue: 0x2438)
    public static let sprmPWAlignFont = try! Sprm(rawValue: 0x4439)
    public static let sprmPFrameTextFlow = try! Sprm(rawValue: 0x443A)
    public static let sprmPOutLvl = try! Sprm(rawValue: 0x2640)
    public static let sprmPFBiDi = try! Sprm(rawValue: 0x2441)
    public static let sprmPFNumRMIns = try! Sprm(rawValue: 0x2443)
    public static let sprmPNumRM = try! Sprm(rawValue: 0xC645)
    public static let sprmPHugePapx = try! Sprm(rawValue: 0x6646)
    public static let sprmPFUsePgsuSettings = try! Sprm(rawValue: 0x2447)
    public static let sprmPFAdjustRight = try! Sprm(rawValue: 0x2448)
    public static let sprmPItap = try! Sprm(rawValue: 0x6649)
    public static let sprmPDtap = try! Sprm(rawValue: 0x664A)
    public static let sprmPFInnerTableCell = try! Sprm(rawValue: 0x244B)
    public static let sprmPFInnerTtp = try! Sprm(rawValue: 0x244C)
    public static let sprmPShd = try! Sprm(rawValue: 0xC64D)
    public static let sprmPBrcTop = try! Sprm(rawValue: 0xC64E)
    public static let sprmPBrcLeft = try! Sprm(rawValue: 0xC64F)
    public static let sprmPBrcBottom = try! Sprm(rawValue: 0xC650)
    public static let sprmPBrcRight = try! Sprm(rawValue: 0xC651)
    public static let sprmPBrcBetween = try! Sprm(rawValue: 0xC652)
    public static let sprmPBrcBar = try! Sprm(rawValue: 0xC653)
    public static let sprmPDxcRight = try! Sprm(rawValue: 0x4455)
    public static let sprmPDxcLeft = try! Sprm(rawValue: 0x4456)
    public static let sprmPDxcLeft1 = try! Sprm(rawValue: 0x4457)
    public static let sprmPDylBefore = try! Sprm(rawValue: 0x4458)
    public static let sprmPDylAfter = try! Sprm(rawValue: 0x4459)
    public static let sprmPFOpenTch = try! Sprm(rawValue: 0x245A)
    public static let sprmPFDyaBeforeAuto = try! Sprm(rawValue: 0x245B)
    public static let sprmPFDyaAfterAuto = try! Sprm(rawValue: 0x245C)
    public static let sprmPDxaRight = try! Sprm(rawValue: 0x845D)
    public static let sprmPDxaLeft = try! Sprm(rawValue: 0x845E)
    public static let sprmPNest = try! Sprm(rawValue: 0x465F)
    public static let sprmPDxaLeft1 = try! Sprm(rawValue: 0x8460)
    public static let sprmPJc = try! Sprm(rawValue: 0x2461)
    public static let sprmPFNoAllowOverlap = try! Sprm(rawValue: 0x2462)
    public static let sprmPWall = try! Sprm(rawValue: 0x2664)
    public static let sprmPIpgp = try! Sprm(rawValue: 0x6465)
    public static let sprmPCnf = try! Sprm(rawValue: 0xC666)
    public static let sprmPRsid = try! Sprm(rawValue: 0x6467)
    public static let sprmPIstdListPermute = try! Sprm(rawValue: 0xC669)
    public static let sprmPTableProps = try! Sprm(rawValue: 0x646B)
    public static let sprmPTIstdInfo = try! Sprm(rawValue: 0xC66C)
    public static let sprmPFContextualSpacing = try! Sprm(rawValue: 0x246D)
    public static let sprmPPropRMark = try! Sprm(rawValue: 0xC66F)
    public static let sprmPFMirrorIndents = try! Sprm(rawValue: 0x2470)
    public static let sprmPTtwo = try! Sprm(rawValue: 0x2471)
    public static let sprmTJc90 = try! Sprm(rawValue: 0x5400)
    public static let sprmTDxaLeft = try! Sprm(rawValue: 0x9601)
    public static let sprmTDxaGapHalf = try! Sprm(rawValue: 0x9602)
    public static let sprmTFCantSplit90 = try! Sprm(rawValue: 0x3403)
    public static let sprmTTableHeader = try! Sprm(rawValue: 0x3404)
    public static let sprmTTableBorders80 = try! Sprm(rawValue: 0xD605)
    public static let sprmTDyaRowHeight = try! Sprm(rawValue: 0x9407)
    public static let sprmTDefTable = try! Sprm(rawValue: 0xD608)
    public static let sprmTDefTableShd80 = try! Sprm(rawValue: 0xD609)
    public static let sprmTTlp = try! Sprm(rawValue: 0x740A)
    public static let sprmTFBiDi = try! Sprm(rawValue: 0x560B)
    public static let sprmTDefTableShd3rd = try! Sprm(rawValue: 0xD60C)
    public static let sprmTPc = try! Sprm(rawValue: 0x360D)
    public static let sprmTDxaAbs = try! Sprm(rawValue: 0x940E)
    public static let sprmTDyaAbs = try! Sprm(rawValue: 0x940F)
    public static let sprmTDxaFromText = try! Sprm(rawValue: 0x9410)
    public static let sprmTDyaFromText = try! Sprm(rawValue: 0x9411)
    public static let sprmTDefTableShd = try! Sprm(rawValue: 0xD612)
    public static let sprmTTableBorders = try! Sprm(rawValue: 0xD613)
    public static let sprmTTableWidth = try! Sprm(rawValue: 0xF614)
    public static let sprmTFAutofit = try! Sprm(rawValue: 0x3615)
    public static let sprmTDefTableShd2nd = try! Sprm(rawValue: 0xD616)
    public static let sprmTWidthBefore = try! Sprm(rawValue: 0xF617)
    public static let sprmTWidthAfter = try! Sprm(rawValue: 0xF618)
    public static let sprmTFKeepFollow = try! Sprm(rawValue: 0x3619)
    public static let sprmTBrcTopCv = try! Sprm(rawValue: 0xD61A)
    public static let sprmTBrcLeftCv = try! Sprm(rawValue: 0xD61B)
    public static let sprmTBrcBottomCv = try! Sprm(rawValue: 0xD61C)
    public static let sprmTBrcRightCv = try! Sprm(rawValue: 0xD61D)
    public static let sprmTDxaFromTextRight = try! Sprm(rawValue: 0x941E)
    public static let sprmTDyaFromTextBottom = try! Sprm(rawValue: 0x941F)
    public static let sprmTSetBrc80 = try! Sprm(rawValue: 0xD620)
    public static let sprmTInsert = try! Sprm(rawValue: 0x7621)
    public static let sprmTDelete = try! Sprm(rawValue: 0x5622)
    public static let sprmTDxaCol = try! Sprm(rawValue: 0x7623)
    public static let sprmTMerge = try! Sprm(rawValue: 0x5624)
    public static let sprmTSplit = try! Sprm(rawValue: 0x5625)
    public static let sprmTTextFlow = try! Sprm(rawValue: 0x7629)
    public static let sprmTVertMerge = try! Sprm(rawValue: 0xD62B)
    public static let sprmTVertAlign = try! Sprm(rawValue: 0xD62C)
    public static let sprmTSetShd = try! Sprm(rawValue: 0xD62D)
    public static let sprmTSetShdOdd = try! Sprm(rawValue: 0xD62E)
    public static let sprmTSetBrc = try! Sprm(rawValue: 0xD62F)
    public static let sprmTCellPadding = try! Sprm(rawValue: 0xD632)
    public static let sprmTCellSpacingDefault = try! Sprm(rawValue: 0xD633)
    public static let sprmTCellPaddingDefault = try! Sprm(rawValue: 0xD634)
    public static let sprmTCellWidth = try! Sprm(rawValue: 0xD635)
    public static let sprmTFitText = try! Sprm(rawValue: 0xF636)
    public static let sprmTFCellNoWrap = try! Sprm(rawValue: 0xD639)
    public static let sprmTIstd = try! Sprm(rawValue: 0x563A)
    public static let sprmTCellPaddingStyle = try! Sprm(rawValue: 0xD63E)
    public static let sprmTCellFHideMark = try! Sprm(rawValue: 0xD642)
    public static let sprmTSetShdTable = try! Sprm(rawValue: 0xD660)
    public static let sprmTWidthIndent = try! Sprm(rawValue: 0xF661)
    public static let sprmTCellBrcType = try! Sprm(rawValue: 0xD662)
    public static let sprmTFBiDi90 = try! Sprm(rawValue: 0x5664)
    public static let sprmTFNoAllowOverlap = try! Sprm(rawValue: 0x3465)
    public static let sprmTFCantSplit = try! Sprm(rawValue: 0x3466)
    public static let sprmTPropRMark = try! Sprm(rawValue: 0xD667)
    public static let sprmTWall = try! Sprm(rawValue: 0x3668)
    public static let sprmTIpgp = try! Sprm(rawValue: 0x7469)
    public static let sprmTCnf = try! Sprm(rawValue: 0xD66A)
    public static let sprmTDefTableShdRaw = try! Sprm(rawValue: 0xD670)
    public static let sprmTDefTableShdRaw2nd = try! Sprm(rawValue: 0xD671)
    public static let sprmTDefTableShdRaw3rd = try! Sprm(rawValue: 0xD672)
    public static let sprmTRsid = try! Sprm(rawValue: 0x7479)
    public static let sprmTCellVertAlignStyle = try! Sprm(rawValue: 0x347C)
    public static let sprmTCellNoWrapStyle = try! Sprm(rawValue: 0x347D)
    public static let sprmTCellBrcTopStyle = try! Sprm(rawValue: 0xD47F)
    public static let sprmTCellBrcBottomStyle = try! Sprm(rawValue: 0xD680)
    public static let sprmTCellBrcLeftStyle = try! Sprm(rawValue: 0xD681)
    public static let sprmTCellBrcRightStyle = try! Sprm(rawValue: 0xD682)
    public static let sprmTCellBrcInsideHStyle = try! Sprm(rawValue: 0xD683)
    public static let sprmTCellBrcInsideVStyle = try! Sprm(rawValue: 0xD684)
    public static let sprmTCellBrcTL2BRStyle = try! Sprm(rawValue: 0xD685)
    public static let sprmTCellBrcTR2BLStyle = try! Sprm(rawValue: 0xD686)
    public static let sprmTCellShdStyle = try! Sprm(rawValue: 0xD687)
    public static let sprmTCHorzBands = try! Sprm(rawValue: 0x3488)
    public static let sprmTCVertBands = try! Sprm(rawValue: 0x3489)
    public static let sprmTJc = try! Sprm(rawValue: 0x548A)
    public static let sprmScnsPgn = try! Sprm(rawValue: 0x3000)
    public static let sprmSiHeadingPgn = try! Sprm(rawValue: 0x3001)
    public static let sprmSDxaColWidth = try! Sprm(rawValue: 0xF203)
    public static let sprmSDxaColSpacing = try! Sprm(rawValue: 0xF204)
    public static let sprmSFEvenlySpaced = try! Sprm(rawValue: 0x3005)
    public static let sprmSFProtected = try! Sprm(rawValue: 0x3006)
    public static let sprmSDmBinFirst = try! Sprm(rawValue: 0x5007)
    public static let sprmSDmBinOther = try! Sprm(rawValue: 0x5008)
    public static let sprmSBkc = try! Sprm(rawValue: 0x3009)
    public static let sprmSFTitlePage = try! Sprm(rawValue: 0x300A)
    public static let sprmSCcolumns = try! Sprm(rawValue: 0x500B)
    public static let sprmSDxaColumns = try! Sprm(rawValue: 0x900C)
    public static let sprmSNfcPgn = try! Sprm(rawValue: 0x300E)
    public static let sprmSFPgnRestart = try! Sprm(rawValue: 0x3011)
    public static let sprmSFEndnote = try! Sprm(rawValue: 0x3012)
    public static let sprmSLnc = try! Sprm(rawValue: 0x3013)
    public static let sprmSNLnnMod = try! Sprm(rawValue: 0x5015)
    public static let sprmSDxaLnn = try! Sprm(rawValue: 0x9016)
    public static let sprmSDyaHdrTop = try! Sprm(rawValue: 0xB017)
    public static let sprmSDyaHdrBottom = try! Sprm(rawValue: 0xB018)
    public static let sprmSLBetween = try! Sprm(rawValue: 0x3019)
    public static let sprmSVjc = try! Sprm(rawValue: 0x301A)
    public static let sprmSLnnMin = try! Sprm(rawValue: 0x501B)
    public static let sprmSPgnStart97 = try! Sprm(rawValue: 0x501C)
    public static let sprmSBOrientation = try! Sprm(rawValue: 0x301D)
    public static let sprmSXaPage = try! Sprm(rawValue: 0xB01F)
    public static let sprmSYaPage = try! Sprm(rawValue: 0xB020)
    public static let sprmSDxaLeft = try! Sprm(rawValue: 0xB021)
    public static let sprmSDxaRight = try! Sprm(rawValue: 0xB022)
    public static let sprmSDyaTop = try! Sprm(rawValue: 0x9023)
    public static let sprmSDyaBottom = try! Sprm(rawValue: 0x9024)
    public static let sprmSDzaGutter = try! Sprm(rawValue: 0xB025)
    public static let sprmSDmPaperReq = try! Sprm(rawValue: 0x5026)
    public static let sprmSFBiDi = try! Sprm(rawValue: 0x3228)
    public static let sprmSFRTLGutter = try! Sprm(rawValue: 0x322A)
    public static let sprmSBrcTop80 = try! Sprm(rawValue: 0x702B)
    public static let sprmSBrcLeft80 = try! Sprm(rawValue: 0x702C)
    public static let sprmSBrcBottom80 = try! Sprm(rawValue: 0x702D)
    public static let sprmSBrcRight80 = try! Sprm(rawValue: 0x702E)
    public static let sprmSPgbProp = try! Sprm(rawValue: 0x522F)
    public static let sprmSDxtCharSpace = try! Sprm(rawValue: 0x7030)
    public static let sprmSDyaLinePitch = try! Sprm(rawValue: 0x9031)
    public static let sprmSClm = try! Sprm(rawValue: 0x5032)
    public static let sprmSTextFlow = try! Sprm(rawValue: 0x5033)
    public static let sprmSBrcTop = try! Sprm(rawValue: 0xD234)
    public static let sprmSBrcLeft = try! Sprm(rawValue: 0xD235)
    public static let sprmSBrcBottom = try! Sprm(rawValue: 0xD236)
    public static let sprmSBrcRight = try! Sprm(rawValue: 0xD237)
    public static let sprmSWall = try! Sprm(rawValue: 0x3239)
    public static let sprmSRsid = try! Sprm(rawValue: 0x703A)
    public static let sprmSFpc = try! Sprm(rawValue: 0x303B)
    public static let sprmSRncFtn = try! Sprm(rawValue: 0x303C)
    public static let sprmSRncEdn = try! Sprm(rawValue: 0x303E)
    public static let sprmSNFtn = try! Sprm(rawValue: 0x503F)
    public static let sprmSNfcFtnRef = try! Sprm(rawValue: 0x5040)
    public static let sprmSNEdn = try! Sprm(rawValue: 0x5041)
    public static let sprmSNfcEdnRef = try! Sprm(rawValue: 0x5042)
    public static let sprmSPropRMark = try! Sprm(rawValue: 0xD243)
    public static let sprmSPgnStart = try! Sprm(rawValue: 0x7044)
    public static let sprmPicBrcTop80 = try! Sprm(rawValue: 0x6C02)
    public static let sprmPicBrcLeft80 = try! Sprm(rawValue: 0x6C03)
    public static let sprmPicBrcBottom80 = try! Sprm(rawValue: 0x6C04)
    public static let sprmPicBrcRight80 = try! Sprm(rawValue: 0x6C05)
    public static let sprmPicBrcTop = try! Sprm(rawValue: 0xCE08)
    public static let sprmPicBrcLeft = try! Sprm(rawValue: 0xCE09)
    public static let sprmPicBrcBottom = try! Sprm(rawValue: 0xCE0A)

}
